package com.example.android_project;

import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.android_project.Adapter.BeritaAdapter;
import com.example.android_project.Models.Kategori;
import com.squareup.picasso.Picasso;

import java.util.ArrayList;
import java.util.List;

public class BeritaActivity extends AppCompatActivity {
    public static final String EXTRA_BERITA="extra_berita ";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_berita);
        RecyclerView teamsView = findViewById(R.id.rv_teams);

        List<Kategori> teams = new ArrayList<>();
        teams.add(new Kategori("https://cdn0-production-images-kly.akamaized.net/P5mLdsFYGNKuT0dgwgNr2OOZA7o=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3047644/original/093517600_1581431309-IMG_20200211_211838.jpg", "Kompetisi Dihentikan, Agenda Barito Putera Berantakan",
                "HomeBolaLiga Indonesia Liga 1 2020 Terhenti Karena Covid-19, Agenda Barito Putera Berantakan Muhammad AdiyaksaMuhammad Adiyaksa  25 Mar 2020, 21:20 WIB  Djadjang Nurdjaman Pelatih Barito Putera Djadjang Nurdjaman. - Agenda Barito Putera berantakan setelah PSSI terpaksa memberhentikan sementara Shopee Liga 1 2020 hingga batas waktu yang belum ditentukan. Jadwal latihan yang jatuh pada hari ini, Rabu (25/3/2020) ikut dibatalkan.  Wabah virus Corona yang makin meluas di Indonesia membuat PSSI tak mau mengambil risiko. Keputusan menyetop Shopee Liga 1 selama minimal dua pekan direvisi.  Awalnya kami akan berkumpul pada hari ini. Tapi mengikuti perkembangan nasional dan sekarang ini, manajemen meminta kami untuk menjadwal ulang agenda tim, kata pelatih Barito Putera, Djadjang Nurdjaman dinukil dari laman Liga Indonesia.  Arsitek asal Sumedang, Jawa Barat itu masih buta dengan kegiatan tim selama penangguhan kompetisi. Barito Putera disebutnya masih menunggu instruksi dari PT Liga Indonesia Baru (LIB) selaku operator kompetisi.  Jadi, belum pasti kapan kami akan memulai latihan kembali. Kami masih menunggu kepastian situasi terkait wabah virus Corona, kata pria yang karib dipanggil Djadjang tersebut."));
        teams.add(new Kategori("https://cdn0-production-images-kly.akamaized.net/Q4VWzcweOj4FrI4OoE-dV_QrpOI=/0x0:0x0/1280x720/filters:quality(75):strip_icc():format(jpeg):watermark(kly-media-production/assets/images/watermarks/bola/watermark-color-landscape-new.png,1205,20,0)/kly-media-production/medias/3082922/original/061912200_1584884125-20200306IQ_Persita_Tangerang_Vs_PSM_Makassar_30.JPG", "Kelanjutan Kompetisi Tak Pasti, Persita Buka Opsi Potong Gaji Pemain"," Ketidakpastian bergulirnya kembali kompetisi Shopee Liga 1 2020 mulai membuat Persita Tangerang khawatir. Klub promosi tersebut membuka opsi untuk memotong gaji pemain, pelatih, dan ofisial.  PSSI resmi menghentikan Shopee Liga 1 2020 dan seluruh kegiatan sepak bola di Indonesia mulai 22 Maret 2020. Keputusan itu diambil karena darurat corona yang sedang melanda Indonesia. PSSI tak bisa memberikan garansi kapan kompetisi elite Indonesia itu kembali bergulir. Situasinya akan bergantung pada kondisi yang ditimbulkan oleh peningkatan virus bernama lain Covid-19 itu.  Manajer Persita Tangerang, I Nyoman Suryanthara, mengaku berencana memotong gaji pemain mulai April 2020. Langkah itu dilakukan karena ketidakpastian dari kompetisi. Pemotongan gaji pemain dianggap sebagai solusi tepat buat Persita. Namun, langkah ini akan diambil jika Shopee Liga 1 2020 hanya dihentikan sementara dan berpeluang dilanjutkan. Persita Tangerang saat ini sedang meliburkan skuatnya hingga waktu yang belum ditentukan. Belum diketahui kapan tim asuhan Widodo Cahyono Putro itu akan kembali berlatih."));
        teams.add(new Kategori("https://cdn1-production-images-kly.akamaized.net/c40QIqXMQEVmjzSEFKNg3w60GZ0=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2874750/original/058508600_1565103447-_R__0232.JPG", "Andritany Ardhiyasa: Keputusan Penghentian Kompetisi Sudah Tepat","Kiper Persija Jakarta, Andritany Ardhiyasa, menyebut keputusan ini tepat.  Shopee Liga 1 2020 sedang jeda seiring dibatalkannya jadwal pertandingan FIFA Matchday. Pekan keempat musim ini seharusnya kembali bergulir pada 3-5 April 2020. Namun, rencana tersebut urung terealisasi mengingat situasi Indonesia yang tak kondusif. PSSI kemudian mengambil keputusan untuk menghentikan sementara semua kegiatan sepak bola yang berada di Indonesia.  Andritany Ardhiyasa, sejak PSSI menunda kompetisi, pesimistis akan kelanjutan sepak bola tertinggi di Indonesia itu. Apalagi, sampai saat ini jumlah kasus positif Covid-19 di Indonesia meningkat setiap harinya.  Hingga kini belum ada titik terang kapan cobaan ini akan berakhir. Sinyal liga Indonesia akan kembali dilanjutkan juga masih belum terlihat. Dengan melihat berbagai perkembangan kasus virus ini dari hari ke hari, kecil kemungkinan liga Indonesia akan bergulir kembali dalam waktu dekat, kata Andritany dalam situs pribadi miliknya.  Kiper berusia 28 tahun itu menyebut, mustahil menggelar pertandingan meskipun tanpa kehadiran penonton.  Saya sebagai pemain setuju dengan keputusan para pemangku kepentingan yang menunda jadwal liga karena memang izin keramaian untuk menyelenggarakan pertandingan akan sulit didapatkan dari pihak keamanan, ujar Andritany.  Kalau pun pertandingan tetap berjalan tanpa kehadiran penonton, saya rasa klub-klub juga akan merasa keberatan karena mereka tidak mendapat pemasukan dari penjualan tiket, tegas kapten Persija Jakarta itu."));
        teams.add(new Kategori("https://cdn1-production-images-kly.akamaized.net/5W6T5DTjF57OX9mv54ghdolBEOg=/0x0:0x0/1280x720/filters:quality(75):strip_icc():format(jpeg):watermark(kly-media-production/assets/images/watermarks/bola/watermark-color-landscape-new.png,1205,20,0)/kly-media-production/medias/3066498/original/005841600_1583216375-20200302IQ_Tira_Persikabo_Vs_Arema_FC_11.jpg", "Rahasia Arema FC Menjaga Tradisi Mencetak Pemain Berkarakter Ngotot","- Arema FC mengalami start yang kurang mulu di awal Shopee Liga 1 2020. Tiga laga pertama musim ini berakhir dengan satu kemenangan dan dua kekalahan. Singo Edan pun harus puas dengan hanya mengoleksi tiga poin dan berada di peringkat ke-12 dalam klasemen Liga 1 2020. Namun, ada satu hal positif yang berhasil didapatkan oleh Arema FC pada awal musim ini. Singo Edan kembali mengorbitkan pemain dengan karakter ngotot khas Malang. Kushedya Hari Yudo yang menjadi pemain lokal Arema FC pada musim ini merupakan satu contohnya. Karier Yudo sudah terlihat cemerlang sejak memperkuat PSS Sleman pada musim lalu. Kini Yudo langsung berkibar dengan menctak dua gol pada pertandingan pertama Arema FC di Shopee Liga 1 2020. Tercatat pemain asli Malang ini pun selalu menjadi pemain inti dalam tiga pertandingan yang sudah dijalani oleh Singo Edan, di mana hal itu tentu memberinya kesempatan untuk dilirik memperkuat Timnas Indonesia. Ini bukan pertama kalinya Arema FC mengorbitkan pemain lokal Malang. Pada musim lalu, Arema FC mengorbitkan Dedik Setiawan. Striker yang sebelumnya lekat dengan image pemain tarkam itu sukses bersama Singo Edan hingga menembus Timnas Indonesia. Sayang, cedera lutut yang dialaminya hingga naik meja operasi membuat musimnya bersama Arema FC berakhir tidak manis. Setelah ditelusuri dari para asisten pelatih, ternyata mereka memang punya insting untuk mengorbitan putra daerah. Seperti yang terjadi saat awal perekrutan Dedik di pertengahan musim 2016 silam."));
        teams.add(new Kategori("https://cdn0-production-images-kly.akamaized.net/CdExQH_5KPVq3k-h6FlEkWexPhw=/108x159:962x640/1280x720/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1828253/original/063651600_1515670510-logo_psms.jpg", "PSMS Medan Perkenalkan 26 Skuat untuk Mengarungi Liga 2 2020"," PSMS Medan akan berkekuatan 26 pemain untuk mengarungi ketatnya kompetisi Shopee Liga 2 2020. Manajemen tim telah memperkenalkan skuatnya dalam sebuah acara di Focal Point Ringroad Jalan Gagak Hitam Medan, Jumat (13/3/2020) malam. Selain perkenalan pemain, PSMS juga menampilkan jersey untk Liga 2. Warna hijau sebagai warna kebesaran kembali digunakan. Acara ini dihadiri perwakilan sponsor. Seperti diketahui, PSMS disponsori oleh dua sponsor besar, yakni Pelindo dan Bank Sumut. Sementara untuk apparel, PSMS memilih Adhoc Apparel. Manajer sekaligus penanggung jawab tim Mulyadi Simatupang mengaku puas dengan acara yang berlangsung semarak. Kita harapkan masyarakat semakin mendukung PSMS agar nantinya lolos ke Liga 1, ujar Mulyadi Simatupang. Ketua Asprov PSSI Sumut diwakili Prof Fidel Ganis Siregar juga berharap PSMS lolos ke Liga 1.  Saya berharap pemain berjuang mati-matian agar PSMS lolos ke Liga 1 katanya. Tim Nasional Indonesia merupakan hasil seleksi pemain-pemain sepakbola terbaik berkebangsaan IndonesiaTimnas Indonesia. Jakarta - PSMS Medan akan berkekuatan 26 pemain untuk mengarungi ketatnya kompetisi Shopee Liga 2 2020. Manajemen tim telah memperkenalkan skuatnya dalam sebuah acara di Focal Point Ringroad Jalan Gagak Hitam Medan, Jumat (13/3/2020) malam. Selain perkenalan pemain, PSMS juga menampilkan jersey untk Liga 2. Warna hijau sebagai warna kebesaran kembali digunakan. Acara ini dihadiri perwakilan sponsor. Seperti diketahui, PSMS disponsori oleh dua sponsor besar, yakni Pelindo dan Bank Sumut. Sementara untuk apparel, PSMS memilih Adhoc Apparel. Manajer sekaligus penanggung jawab tim Mulyadi Simatupang mengaku puas dengan acara yang berlangsung semarak. Kita harapkan masyarakat semakin mendukung PSMS agar nantinya lolos ke Liga 1, ujar Mulyadi Simatupang. Ketua Asprov PSSI Sumut diwakili Prof Fidel Ganis Siregar juga berharap PSMS lolos ke Liga 1.  Saya berharap pemain berjuang mati-matian agar PSMS lolos ke Liga 1, katanya."));
        teams.add(new Kategori("https://cdn1-production-images-kly.akamaized.net/rt91aNlmf9EtMO0renIjBEZMSEE=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3078034/original/094204900_1584361584-3_Klub_Promosi.jpg", "Sorotan: Performa 3 Tim Promosi Shopee Liga 1 2020, Siapa Terburuk?","telah bergulir hingga pekan ketiga. Tiga tim promosi, yakni Persik Kediri, Persiraja Banda Aceh, dan Persita Tangerang melaluinya dengan hasil yang berbeda. Siapa tim yang paling melempem? Secara garis besar, ketiga tim promosi tersebut menampilkan performa yang bisa dibilang tidak terlalu buruk. Hanya ada satu kesamaannya, yakni sulit meraih kemenangan. Persiraja Banda Aceh paling memuaskan. Bersama Persib Bandung, Bali United, PSM Makassar, Persija Jakarta, dan Bhayangkara FC, Persiraja belum menelan kekalahan. Catatan impresif lainnya, Adam Mitter dan kawan-kawan merupakan satu-satunya tim yang belum kebobolan. Ironisnya, mereka juga tercatat sebagai tim yang baru mencetak satu gol di antara 17 peserta Liga 1 lainnya, yakni melalui Defri Riski. Sementara itu, tim asal Jawa Timur, Persik Kediri, yang juga merupakan jawara Liga 2 2019, mampu tampil membanggakan ketika berhasil menahan imbang kandidat juara Liga 1 2020, Persebaya Surabaya, pada partai pembuka di tempat yang terkenal angker buat lawan, Stadion Gelora Bung Tomo dengan skor Persik kemudian sanggup bermain imbang lagi ketika bersua Bhayangkara FC di Stadion Brawijaya. Namun akhirnya, Persiraja mampu mengandaskan tekad Persik meraih kemenangan perdana di kandang sendiri usai tumbang 0-1.  Tim tradisional lainnya, Persita Tangerang, tidak lebih baik. Meski sempat bermain apik dengan menahan tim kuat PSM Makassar dan Bali United, tim berjulukan Pendekar Cisadane itu akhirnya bertekuk lutut kala bertamu ke markas Persikabo dengan skor 1-3.  Bicara klasemen, Persiraja menjadi tim terbaik di antara tim promosi lainnya. Mereka untuk sementara menduduki peringkat ke-7 klasemen Shopee Liga 1 2020. Kendati demikian, bukan berarti tim lainnya memiliki rapor buruk"));
        teams.add(new Kategori("https://cdn1-production-images-kly.akamaized.net/ZsieaAUhVzIyetEEwp0n7dZg5Yg=/0x0:3000x1687/1280x720/filters:quality(75):strip_icc():format(jpeg):watermark(kly-media-production/assets/images/watermarks/bola/watermark-color-landscape-new.png,1205,20,0)/kly-media-production/medias/3064196/original/047629700_1583000793-_MG_1204.JPG", "Menyorot 5 Tim Jatim yang Kehilangan Poin di Kandang, Alarm bagi Persik dan Persebaya","ingga pekan ketiga Shopee Liga 1 2020 ada beberapa tim yang telah kehilangan poin saat tampil di kandangnya. Padahal laga kandang merupakan modal berharga untuk mendulang tiga angka agar bisa bersaing dengan klub-klub lain.  Berikut analisis lima klub asal Jatim yang telah kehilangan poin hingga pekan ketiga lalu. Persik menduduki peringkat teratas. Dengan asumsi jatah kandang harus menang, seharusnya Persik telah memiliki enam poin. Namun, saat ini juara Liga 2 2019 tersebut baru mengumpulkan dua poin dari pertandingan yang dijalani. Dari dua kali laga kandang, Persik hanya mendulang satu poin saat ditahan Bhayangkara FC 1-1.  Ditambah satu poin ketika main seri dengan Persebaya 1-1 pada laga pembuka. Persik telah kehilangan empat poin kandang.  Posisi kedua ditempati Persebaya Surabaya. Bajul Ijo juga telah kecolongan empat angka di kandang, ketika dipaksa main seri dengan Persik, dan takluk 3-4 dari Persipura Jayapura.  Meski sama-sama kehilangan empat poin, Persebaya lebih baik dibanding Persik. Tim asuhan Aji Santoso ini baru bermain dua kali, sedangkan Persik tiga kali.  Tempat ketiga diduduki Persela. Tim asal Kota Soto ini menghuni dasar klasemen sementara tanpa kemenangan. Tapi, sebenarnya, nasib Persema lebih baik daripada Persik dan Persebaya. Anak asuh Nilmaizar ini hanya kehilangan tiga poin kandang saat ditundukkan PSIS 2-3."));
        teams.add(new Kategori("https://cdn0-production-images-kly.akamaized.net/I7aNtq-4kIO2LLVvvWVf8gMhOg0=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3051236/original/084271000_1581757548-IMG_20200215_150708.jpg", "Nasib Apes 3 Pemain Asing di Shopee Liga 1 2020","Beberapa klub Shopee Liga 1 2020 melakukan pencoretan pemain asing ketika kompetisi menjelang atau sudah dimulai.  Persela Lamongan memutus kontrak dua pemain asing, yakni Jasmine Mecinovic dan Shunsuke Nakamura. Sementara, Persik Kediri terpaksa membatalkan kontrak Patrick Bordon (Slovenia), karena terbukti yang bersangkutan punya riwayat cedera MCL dan ACL. Perbedaannya, Mecinovic dan Nakamura, sempat memperkuat Laskar Jaka Tingkir di turnamen pra-musim Piala Gubernur Jatim dan dua laga di Liga 1. Sedangkan Bordon sama sekali belum mencicipi kerasnya sepakbola Indonesia.  Namun, ketiganya mengalami nasib sama, yakni terkatung-katung setelah pencoretan itu. Mereka tak bisa langsung pulang ke negaranya. Sebagai pemain profesional, ketiganya tetap berlatih di klubnya untuk menjaga kebugaran mereka. Saat ini, Jasmine Mecinovic dan Shunsuke Nakamura masih ikut latihan bersama Eki Taufik dkk. Itu pula yang dilakukan Patrick Bordon, ketika positif tak dipakai Persik.Striker jangkung ini ingin memikat manajemen dan pelatih dengan terus berlatih keras. Dia berharap manajemen berubah pikiran tidak mencoretnya. Padahal saat itu, Persik telah mendatangkan pemain asal Serbia, Nikola Asceric sebagai penggantinya. Saya profesional. Uang bagi saya bukan segalanya. Saya hanya ingin main bola, kata Patrick Bordon yang merupakan jebolan klub Lecce, Italia."));

        BeritaAdapter adapter=new BeritaAdapter(this, teams);
        teamsView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(this);
        teamsView.setLayoutManager(layoutManager);
    }
}
